// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQbFDduldBL9zdi01zSoYh5HzeR29jYu8',
    appId: '1:860650147265:web:5e8f2e2081f263f99eb340',
    messagingSenderId: '860650147265',
    projectId: 'my-chat-app-17e74',
    authDomain: 'my-chat-app-17e74.firebaseapp.com',
    storageBucket: 'my-chat-app-17e74.appspot.com',
    measurementId: 'G-567XNH92K3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZYDLKJlXEUBtSd7Z3vT154SqeK7Q__f8',
    appId: '1:860650147265:android:c983af4b46b5c7679eb340',
    messagingSenderId: '860650147265',
    projectId: 'my-chat-app-17e74',
    storageBucket: 'my-chat-app-17e74.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARn0ZzmwBKFqLOoBxSMTjEMpBeuve4olE',
    appId: '1:860650147265:ios:e2f62e8987cf7fc49eb340',
    messagingSenderId: '860650147265',
    projectId: 'my-chat-app-17e74',
    storageBucket: 'my-chat-app-17e74.appspot.com',
    iosBundleId: 'com.example.myChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARn0ZzmwBKFqLOoBxSMTjEMpBeuve4olE',
    appId: '1:860650147265:ios:e2f62e8987cf7fc49eb340',
    messagingSenderId: '860650147265',
    projectId: 'my-chat-app-17e74',
    storageBucket: 'my-chat-app-17e74.appspot.com',
    iosBundleId: 'com.example.myChatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQbFDduldBL9zdi01zSoYh5HzeR29jYu8',
    appId: '1:860650147265:web:1bd841e6d6ebf3a99eb340',
    messagingSenderId: '860650147265',
    projectId: 'my-chat-app-17e74',
    authDomain: 'my-chat-app-17e74.firebaseapp.com',
    storageBucket: 'my-chat-app-17e74.appspot.com',
    measurementId: 'G-0MND7JSVQ5',
  );
}
